### ISSUE TITLE
Running exposed to use with iOS mail.app not working

### ISSUE THREAD

**Issue by jipvankuijk** [shenxn/protonmail-bridge-docker#33]
Hello,

I've tried running this on a M1 MacMini and it runs fine, I can IMAP/SMTP into the docker email bridge over LAN or VPN from another Mac. But if I try doing the exact same from an iOS device it shows all folders and unread email count but it does not actually load the emails.

It says "Account Error" "Cannot Get Mail. The mail server "10.0.0.111" is not responding. Verify that you have entered the correct account info in Mail settings"

The exact same settings work fine on a Mac with the Mail.app but not on iOS.

**Comment by shenxn** [comment]
The bridge itself has problem with some mail clients. So maybe it just not working with iOS. There is nothing I can do here.

**Comment by rp-preger** [comment]
Realize this is closed - but @shenxn could be mistaken. The IOS apps work OK with [peroxide](https://github.com/ljanyst/peroxide) which is a fork of [protonmail-bridge](https://github.com/ProtonMail/proton-bridge) from Proton. So it's probably not the IMAP protocol implementation thats the issue. Maybe the IOS incompatibility is introduced when you run the bridge in a container because you have to spoof the source IP of the incoming address to appear to be local? peroxide is able to accept connections from non-local systems, natively.

**Comment by shenxn** [comment]
The only thing to make it work is by using socat
https://github.com/shenxn/protonmail-bridge-docker/blob/6decf657c2270a79274ffa7d607b33333815a10b/build/entrypoint.sh#L26-L27
It is a very simple relay server that relays packets from port 25 to localhost:1025 and it shouldn't be the root cause.

I have checked https://github.com/ljanyst/peroxide and it appears that the project did much more than just allowing non-local connections so it is very possible that peroxide somehow made it work for the iOS app.
