### ISSUE TITLE
Receive mail twice when sending to a ProtonMail hosted email

### ISSUE THREAD

**Issue by Salamafet** [shenxn/protonmail-bridge-docker#82]
I use protonmail-bridge-docker as SMTP server.

When I send email to a proton hosted mail, I receive the mail twice. When sending to another mail provider (gmail, outlook, yahoo...) I receive the mail once (as normal).

I have tested with different senders (Synology, VaultWarden, Gitea...)

I have sent a support ticket to ProtonMail too, but there is only a small chance to get help with a no official client.

**Comment by proteus077** [comment]
Hi Salamafet,

I noticed the same thing today but I found that the reason you see two is because one is the "sent" mail and the other is the "recieved" mail. You will notice one has the "Sent" icon and the other has the "Received" icon:

![image](https://user-images.githubusercontent.com/86278872/227846351-c7053682-f179-4e60-b7f7-f5fa600f3513.png)
![image](https://user-images.githubusercontent.com/86278872/227846381-68cda102-abbd-4fba-a8d8-1a64a7d60724.png)


So not really a bug but perhaps there is a setting within protonmail to hide sent mail when looking at Inbox, unsure about this.

**Comment by Salamafet** [comment]
Hi @proteus077 

Thanks, you're right. I've not noticed that.

> So not really a bug but perhaps there is a setting within protonmail to hide sent mail when looking at Inbox, unsure about this.

There are no settings like that. Maybe the "conversation mode" but I don't want to disable this convenient feature.
